In [1]:
# src/Python/Tutorial/Basic/pointcloud.py

import sys
import numpy as np
sys.path.append("../..")
from py3d import *

In [2]:
print("Load a ply point cloud, print it, and render it")
pcd = read_point_cloud("/data/code3/Open3D/build/lib/TestData/fragment.ply")
print(pcd)


Load a ply point cloud, print it, and render it
PointCloud with 196133 points.


In [3]:
type(pcd)

py3d.PointCloud

In [5]:
pcd_np = np.asarray(pcd.points)
print(pcd_np)

[[0.65234375 0.84686458 2.37890625]
 [0.65234375 0.83984375 2.38430572]
 [0.66737998 0.83984375 2.37890625]
 ...
 [2.00839925 2.39453125 1.88671875]
 [2.00390625 2.39488506 1.88671875]
 [2.00390625 2.39453125 1.88793314]]


In [7]:
pcd_np.shape

(196133, 3)

In [8]:
pcd_np[0,:]

array([0.65234375, 0.84686458, 2.37890625])

In [20]:
draw_geometries([pcd])

In [13]:
print("Downsample the point cloud with a voxel of 0.05")
downpcd = voxel_down_sample(pcd, voxel_size = 0.05)

Downsample the point cloud with a voxel of 0.05


In [14]:
downpcd_np = np.asarray(downpcd.points)

In [15]:
# show downsampled voxel shape
downpcd_np.shape

(4718, 3)

In [12]:
draw_geometries([downpcd])

In [22]:
print("Recompute the normal of the downsampled point cloud")
estimate_normals(downpcd, search_param = KDTreeSearchParamHybrid(
        radius = 0.1, max_nn = 30))

Recompute the normal of the downsampled point cloud


True

In [25]:
draw_geometries([downpcd])

In [26]:
print("Load a polygon volume and use it to crop the original point cloud")
vol = read_selection_polygon_volume("/data/code3/Open3D/build/lib/TestData/Crop/cropped.json")


Load a polygon volume and use it to crop the original point cloud


In [27]:
type(vol)

py3d.SelectionPolygonVolume

In [28]:
# filters out points to obtain the chair.
chair = vol.crop_point_cloud(pcd)
draw_geometries([chair])
print("")

In [29]:
print("Paint chair")
chair.paint_uniform_color([1, 0.706, 0])
draw_geometries([chair])
print("")

Paint chair



In [30]:
print("Paint chair in green")
chair.paint_uniform_color([0, 1, 0])
draw_geometries([chair])

Paint chair in green
