# Working with NumPy
http://www.open3d.org/docs/tutorial/Basic/working_with_numpy.html

Data structure of Open3D is natively compatible with NumPy buffer. The following tutorial generates a variant of sync function using NumPy and visualizes the function using Open3D.

In [2]:
# src/Python/Tutorial/Basic/working_with_numpy.py

import copy
import numpy as np
from open3d import *

## From NumPy to Open3D

In [3]:
# generate some neat n times 3 matrix using a variant of sync function
x = np.linspace(-3, 3, 401)
mesh_x, mesh_y = np.meshgrid(x,x)
z = np.sinc((np.power(mesh_x,2)+np.power(mesh_y,2)))
xyz = np.zeros((np.size(mesh_x),3))
xyz[:,0] = np.reshape(mesh_x,-1)
xyz[:,1] = np.reshape(mesh_y,-1)
xyz[:,2] = np.reshape(z,-1)
print('xyz')
print(xyz)

xyz
[[-3.00000000e+00 -3.00000000e+00 -3.89817183e-17]
 [-2.98500000e+00 -3.00000000e+00 -4.94631078e-03]
 [-2.97000000e+00 -3.00000000e+00 -9.52804798e-03]
 ...
 [ 2.97000000e+00  3.00000000e+00 -9.52804798e-03]
 [ 2.98500000e+00  3.00000000e+00 -4.94631078e-03]
 [ 3.00000000e+00  3.00000000e+00 -3.89817183e-17]]


In [4]:
# Pass xyz to Open3D.PointCloud and visualize
pcd = PointCloud()
pcd.points = Vector3dVector(xyz)
write_point_cloud("/data/code6/Open3D/build/lib/TestData/sync.ply", pcd)

True

In [ ]:
# Load saved point cloud and transform it into NumPy array

pcd_load = read_point_cloud("/data/code6/Open3D/build/lib/TestData/sync.ply")
xyz_load = np.asarray(pcd_load.points)
print('xyz_load')

print(xyz_load)

# visualization
draw_geometries([pcd_load])

## From Open3D to NumPy

In [ ]:
# Load saved point cloud and transform it into NumPy array
pcd_load = read_point_cloud("../../TestData/sync.ply")
xyz_load = np.asarray(pcd_load.points)
print('xyz_load')
print(xyz_load)

# visualization
draw_geometries([pcd_load])